package cn.longer233.gamenarrator.task.application;

import cn.longer233.gamenarrator.task.domain.*;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

public record VideoTaskView(
        UUID id,
        String name,
        String gameCategory,
        CommentaryStyle commentaryStyle,
        int targetDurationSeconds,
        EditingScope editingScope,
        String taskBrief,
        TaskStatus status,
        Double durationSeconds,
        Integer videoWidth,
        Integer videoHeight,
        Double framesPerSecond,
        String videoCodec,
        String audioCodec,
        String extractedAudioPath,
        String sceneManifestPath,
        Integer detectedSceneCount,
        String transcriptText,
        String transcriptTextPath,
        String subtitlePath,
        String transcriptJsonPath,
        String visualSummary,
        String visualAnalysisPath,
        Integer analyzedFrameCount,
        String highlightSummary,
        String highlightManifestPath,
        Integer selectedHighlightCount,
        String generatedTitle,
        String scriptSynopsis,
        String generatedNarration,
        String generatedScriptPath,
        Integer generatedScriptSegmentCount,
        String voiceManifestPath,
        Integer generatedVoiceSegmentCount,
        String timelinePath,
        Double plannedOutputDurationSeconds,
        Integer voiceOverflowCount,
        String renderedVideoPath,
        String generatedSubtitlePath,
        Long renderedFileSizeBytes,
        boolean storyboardReviewEnabled,
        boolean storyboardApproved,
        boolean cloudVisionEnabled,
        boolean aiScriptEnabled,
        boolean aiVoiceEnabled,
        boolean autoAssetsEnabled,
        boolean automaticGenerationEnabled,
        String failureReason,
        Instant createdAt,
        List<StageView> stages
) {
    public static VideoTaskView from(VideoTask task) {
        return new VideoTaskView(
                task.getId(),
                task.getName(),
                task.getGameCategory(),
                task.getCommentaryStyle(),
                task.getTargetDurationSeconds(),
                task.getEditingScope(),
                task.getTaskBrief(),
                task.getStatus(),
                task.getDurationSeconds(),
                task.getVideoWidth(),
                task.getVideoHeight(),
                task.getFramesPerSecond(),
                task.getVideoCodec(),
                task.getAudioCodec(),
                task.getExtractedAudioPath(),
                task.getSceneManifestPath(),
                task.getDetectedSceneCount(),
                task.getTranscriptText(),
                task.getTranscriptTextPath(),
                task.getSubtitlePath(),
                task.getTranscriptJsonPath(),
                task.getVisualSummary(),
                task.getVisualAnalysisPath(),
                task.getAnalyzedFrameCount(),
                task.getHighlightSummary(),
                task.getHighlightManifestPath(),
                task.getSelectedHighlightCount(),
                task.getGeneratedTitle(),
                task.getScriptSynopsis(),
                task.getGeneratedNarration(),
                task.getGeneratedScriptPath(),
                task.getGeneratedScriptSegmentCount(),
                task.getVoiceManifestPath(),
                task.getGeneratedVoiceSegmentCount(),
                task.getTimelinePath(),
                task.getPlannedOutputDurationSeconds(),
                task.getVoiceOverflowCount(),
                task.getRenderedVideoPath(),
                task.getGeneratedSubtitlePath(),
                task.getRenderedFileSizeBytes(),
                task.isStoryboardReviewEnabled(),
                task.isStoryboardApproved(),
                task.isCloudVisionEnabled(),
                task.isAiScriptEnabled(),
                task.isAiVoiceEnabled(),
                task.isAutoAssetsEnabled(),
                task.isAutomaticGenerationEnabled(),
                task.getFailureReason(),
                task.getCreatedAt(),
                task.getStages().stream().map(StageView::from).toList()
        );
    }
}
