plugins {
    id 'com.android.application'
}

android {
    namespace 'cn.longer233.gamenarrator.mobile'
    compileSdk 37

    defaultConfig {
        applicationId 'cn.longer233.gamenarrator.mobile'
        minSdk 29
        targetSdk 37
        versionCode 1
        versionName '0.1.0'
    }
    buildFeatures { buildConfig true }
    packaging { resources.excludes += ['/META-INF/{AL2.0,LGPL2.1}'] }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.media3:media3-exoplayer:1.10.1'
    implementation 'androidx.media3:media3-ui:1.10.1'
    implementation 'androidx.media3:media3-transformer:1.10.1'
    implementation 'androidx.media3:media3-effect:1.10.1'
    testImplementation 'junit:junit:4.13.2'
}
