param([string]$OutputPath = "ANDROID_AI_CONTEXT.md")
$ErrorActionPreference = "Stop"
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$androidRoot = Join-Path $projectRoot "android-app"
$rulesPath = Join-Path $PSScriptRoot "android-ai-rules.zh-CN.md"
$resolvedOutput = Join-Path $projectRoot $OutputPath
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
if (-not (Test-Path -LiteralPath (Join-Path $androidRoot "settings.gradle"))) { throw "Android project not found: $androidRoot" }
if (-not (Test-Path -LiteralPath $rulesPath)) { throw "Android AI rules not found: $rulesPath" }

function Get-AndroidContextFiles {
    $extensions = @(".java", ".kt", ".xml", ".gradle", ".properties", ".md", ".pro")
    $files = Get-ChildItem -LiteralPath $androidRoot -Recurse -File | Where-Object {
        $extensions -contains $_.Extension.ToLowerInvariant() -and
        $_.FullName -notmatch "[\\/](build|\.gradle|\.gradle-dist)[\\/]" -and
        $_.Name -ne "local.properties"
    }
    foreach ($relative in @("frontend/index.html", "frontend/public/app.css", "frontend/public/app.js", "README.md", ".gitignore", "scripts/build-android-apk.ps1", "scripts/export-android-ai-context.ps1", "scripts/android-ai-rules.zh-CN.md")) {
        $path = Join-Path $projectRoot $relative
        if (Test-Path -LiteralPath $path) { Get-Item -LiteralPath $path }
    }
    $files | Sort-Object FullName -Unique
}
function Get-Language([string]$extension) {
    switch ($extension.ToLowerInvariant()) {
        ".java" { "java" }; ".kt" { "kotlin" }; ".xml" { "xml" }; ".gradle" { "groovy" }
        ".properties" { "properties" }; ".ps1" { "powershell" }; ".js" { "javascript" }
        ".css" { "css" }; ".html" { "html" }; default { "text" }
    }
}

$files = @(Get-AndroidContextFiles)
$rules = [IO.File]::ReadAllText($rulesPath, [Text.Encoding]::UTF8)
$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine("# GameNarrator Android - AI Context Bundle")
[void]$builder.AppendLine()
[void]$builder.AppendLine("> Generated: $([DateTimeOffset]::Now.ToString('yyyy-MM-dd HH:mm:ss zzz'))")
[void]$builder.AppendLine("> Files: $($files.Count). Generated by scripts/export-android-ai-context.ps1.")
[void]$builder.AppendLine()
[void]$builder.AppendLine($rules)
[void]$builder.AppendLine()
[void]$builder.AppendLine("## File manifest")
[void]$builder.AppendLine()
foreach ($file in $files) {
    $relative = $file.FullName.Substring($projectRoot.Length).TrimStart("\").Replace("\", "/")
    [void]$builder.AppendLine("- $relative ($($file.Length) bytes)")
}
[void]$builder.AppendLine()
[void]$builder.AppendLine("## Project sources")
[void]$builder.AppendLine()
foreach ($file in $files) {
    $relative = $file.FullName.Substring($projectRoot.Length).TrimStart("\").Replace("\", "/")
    $content = [IO.File]::ReadAllText($file.FullName, [Text.Encoding]::UTF8)
    [void]$builder.AppendLine("### FILE: $relative")
    [void]$builder.AppendLine()
    [void]$builder.AppendLine("~~~~$(Get-Language $file.Extension)")
    [void]$builder.Append($content)
    if (-not $content.EndsWith([Environment]::NewLine)) { [void]$builder.AppendLine() }
    [void]$builder.AppendLine("~~~~")
    [void]$builder.AppendLine()
}
$output = $builder.ToString().TrimEnd("`r", "`n") + [Environment]::NewLine
[IO.File]::WriteAllText($resolvedOutput, $output, $utf8NoBom)
Write-Host "Android AI context updated: $resolvedOutput ($($output.Length) characters)"
