ALTER TABLE video_tasks ADD COLUMN IF NOT EXISTS cloud_vision_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE video_tasks ADD COLUMN IF NOT EXISTS ai_script_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE video_tasks ADD COLUMN IF NOT EXISTS ai_voice_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE video_tasks ADD COLUMN IF NOT EXISTS auto_assets_enabled BOOLEAN NOT NULL DEFAULT TRUE;
