ALTER TABLE video_tasks ADD COLUMN IF NOT EXISTS storyboard_review_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE video_tasks ADD COLUMN IF NOT EXISTS storyboard_approved BOOLEAN NOT NULL DEFAULT TRUE;
